function removeElementInArray(array, element)
{
	for(var index = 0, length = array.length; index < array.length; index++)
	{
		if(array[index] === element)
		{
			array.splice(index,1);
			return true;
		}
	}
	return false;
}

function htmlToPlainText(html) {
	// Create a new div element
	const div = document.createElement('div');
	// Set the HTML content of the div to the input string
	div.innerHTML = html;
	// Retrieve the plain text version of the HTML string
	let text = div.textContent || div.innerText;
	// Remove new lines
	text = text.replace(/\n/g, ' ').replace("Copy code", "");
	// Remove leading and trailing white space
	text = text.trim();
	return text;
}

function getObjectById(id, list) { // created by ChatGPT
    // Iterate over the list of objects
    for (let i = 0; i < list.length; i++) {
        const obj = list[i];

        // Check if the object has an `id` property that matches the given id
        if (obj.id && obj.id === id) {
            // If a match is found, return the object
            return obj;
        }
    }

    // If no match is found, return null
    return null;
}

function getDate() { // generated by ChatGPT
	var date = new Date();
	var options = {year: 'numeric', month: 'long', day: 'numeric'};
	return date.toLocaleString('default', options);
}

function getTime() { // generated by ChatGPT
	var currentDate = new Date();
	var options = {
		hour12: true,
		hour: "numeric",
		minute: "numeric"
	};
	var timeString = currentDate.toLocaleTimeString("default", options);
	return timeString
}

function generateUUID() { // generated by ChatGPT
	// create an array of possible characters for the UUID
	var possibleChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

	// create an empty string that will be used to generate the UUID
	var uuid = "";

	// loop over the possible characters and append a random character to the UUID string
	for (var i = 0; i < 36; i++) {
		uuid += possibleChars.charAt(Math.floor(Math.random() * possibleChars.length));
	}

	// return the generated UUID
	return uuid;
}